Manage installation/removal of the Wazuh plugin
wazuh/wazuh-dashboard pull request #28
Opened 2023-02-21 13:58 UTC by AlexRuiz7

### Description

**Depends on #18**: parts from the pull requests #18, be aware that these changes are shown too. Do not merge this pull request before #18.

------------------

This pull request adds the ability to install the Wazuh plugin using the CLI tools. The version of the plugin installed matches the version of Wazuh defined in the `package.json` file. 
 
```
node@558d18d50820:~/osd$ node src/cli_plugin/dev.js install wazuh
Attempting to transfer from wazuh
Attempting to transfer from https://packages-dev.wazuh.com/pre-release/ui/dashboard/wazuh-4.4.0-1.zip
Transferring 39236823 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete

node@558d18d50820:~/osd$ node src/cli_plugin/dev.js list         
wazuh@4.4.0-03

node@558d18d50820:~/osd$ node src/cli_plugin/dev.js remove wazuh
Removing wazuh...
Plugin removal complete
```

### Issues Resolved
#25 
 
### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-04-19 07:43 UTC, AlexRuiz7 reviewed
[This change](https://github.com/wazuh/wazuh-dashboard/pull/28/commits/291f10a68d1fa189bec63a3100c442a0af2593a0) is not necessary, please, undo it @yenienserrano .

2023-04-20 11:41 UTC, AlexRuiz7 commented on src/cli_plugin/install/settings.js
> +    ? [plugin, generateWazuhPluginUrl(wazuhVersion, plugin)]
We should also handle the `wazuh-security-dashboards-plugin`

2023-04-27 17:44 UTC, Machi3mfl requested changes
## Test

### Add Wazuh via CLI

![image](https://user-images.githubusercontent.com/6089438/234942643-913c7df9-5816-4e7c-bba8-6127cd7f4469.png)

`Error in dashboard`

![image](https://user-images.githubusercontent.com/6089438/234943014-f6a937c4-c83c-4dda-b848-913b2374a514.png)

![image](https://user-images.githubusercontent.com/6089438/234943110-68b255eb-74fc-4e8d-a3bc-093e822b6976.png)

![image](https://user-images.githubusercontent.com/6089438/234943280-a227e696-b49b-4105-835c-2e6edec3bab0.png)

### Remove Wazuh via CLI

![image](https://user-images.githubusercontent.com/6089438/234943599-2112779a-3ab6-4946-b9f8-6e9675cc2f8f.png)

`Same error after remove`

![image](https://user-images.githubusercontent.com/6089438/234943014-f6a937c4-c83c-4dda-b848-913b2374a514.png)


## Solution

- Add ? after wazuhVersion to avoid the error: `cannot read properties of undefined (reading slice)`

![image](https://user-images.githubusercontent.com/6089438/234946241-0cd5fc4a-d980-4d46-bdc9-693104050ab1.png)

### After code modification

![image](https://user-images.githubusercontent.com/6089438/234947371-aac237f2-fc81-4c7c-97ae-9375e75472ff.png)

2023-05-03 11:51 UTC, Machi3mfl approved these changes

2023-05-03 12:15 UTC, Machi3mfl commented
> ## Test
> ### Add Wazuh via CLI
> ![image](https://user-images.githubusercontent.com/6089438/234942643-913c7df9-5816-4e7c-bba8-6127cd7f4469.png)
> 
> `Error in dashboard`
> 
> ![image](https://user-images.githubusercontent.com/6089438/234943014-f6a937c4-c83c-4dda-b848-913b2374a514.png)
> 
> ![image](https://user-images.githubusercontent.com/6089438/234943110-68b255eb-74fc-4e8d-a3bc-093e822b6976.png)
> 
> ![image](https://user-images.githubusercontent.com/6089438/234943280-a227e696-b49b-4105-835c-2e6edec3bab0.png)
> 
> ### Remove Wazuh via CLI
> ![image](https://user-images.githubusercontent.com/6089438/234943599-2112779a-3ab6-4946-b9f8-6e9675cc2f8f.png)
> 
> `Same error after remove`
> 
> ![image](https://user-images.githubusercontent.com/6089438/234943014-f6a937c4-c83c-4dda-b848-913b2374a514.png)
> 
> ## Solution
> * Add ? after wazuhVersion to avoid the error: `cannot read properties of undefined (reading slice)`
> 
> ![image](https://user-images.githubusercontent.com/6089438/234946241-0cd5fc4a-d980-4d46-bdc9-693104050ab1.png)
> 
> ### After code modification
> ![image](https://user-images.githubusercontent.com/6089438/234947371-aac237f2-fc81-4c7c-97ae-9375e75472ff.png)

- The `slice error` fixed in the commit https://github.com/wazuh/wazuh-dashboard/pull/28/commits/bacb28a2eedcddfefc611f831d08fa4c6e128b88
- The server error `Module not found` was solved after re-run bootstrap script

2023-05-08 11:55 UTC, AlexRuiz7 reviewed
Check https://github.com/wazuh/wazuh-dashboard/pull/27#discussion_r1172440934

2023-05-08 17:32 UTC, Machi3mfl commented
> Check https://github.com/wazuh/wazuh-dashboard/pull/27#discussion_r1172440934

Done in commit https://github.com/wazuh/wazuh-dashboard/commit/5fd3e350eef0d105e076a09eea2cf63754322605

2023-05-09 09:15 UTC, merged