Add the development environment Wazuh-dashboards
wazuh/wazuh-dashboard pull request #30
Opened 2023-02-27 11:01 UTC by yenienserrano

### Description
Added the development environment to manage issues in Wazuh-dashboard.
 
### Issues Resolved
- #21 

### Test

You must be able to log in to wazuh-dashboards with the environments.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-03-01 11:54 UTC, Desvelao commented on docker/dev.sh
> +export OPENSEARCH_VERSION=$1 || $(node -e "console.log(require('$REPO_PATH/package.json').version)")
**thought**: if NodeJS is required to run the script, then maybe we could mention this optional requirement in the readme.

2023-03-01 14:57 UTC, Desvelao commented on docker/dev.sh
> +export OPENSEARCH_VERSION=$1 || $(node -e "console.log(require('$REPO_PATH/package.json').version)")
The statement to use NodeJS was removed here: https://github.com/wazuh/wazuh-dashboard/pull/30/commits/3e6e505d5ee38c70e3386fac28d86151a6ac4feb.

2023-03-02 08:03 UTC, Desvelao commented on docker/dev.yml
> +    # entrypoint: ["tail", "-f", "/dev/null"]
**nitpick**: remove if this is not necessary.

2023-04-13 15:28 UTC, AlexRuiz7 requested changes
The proposed solution only works for published versions of OpenSearch as it is based on the Docker images published by them on each release, so we cannot use versions under development using this approach.

I've developed a variant that uses the OpenSearch snapshots, which are generated even for versions under development. The problem is that the snapshots are minimal and do not include any additional plugins, not even the security one, so we cannot use our security plugin in the frontend neither, unlike the solution added here.

As both solutions have advantages and disadvantages, we'll keep both, so we can decide which version to start (with or without security) depending on the situation.

We'll eventually upgrade these tools if we see fit, hopefully solving the limitations of both partial solutions.


```yml
version: "3.9"

services:
  # Runs the bootstrap and exits
  installer:
    image: node:${NODE_VERSION}
    container_name: installer
    volumes:
      - ${REPO_PATH}:/home/node/app
      # - ${SECURITY_PLUGIN_REPO_PATH}:/home/node/app/plugins/security
    user: "1000:1000"
    working_dir: /home/node/app
    command: >
      /bin/bash -c "
        yarn osd bootstrap
      "

  wazuh-dashboard:
    image: node:${NODE_VERSION}
    container_name: wazuh-dashboard
    depends_on:
      installer:
        condition: service_completed_successfully
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to Wazuh Dashboard
    volumes:
      - ${REPO_PATH}:/home/node/app
      # - ${SECURITY_PLUGIN_REPO_PATH}:/home/node/app/plugins/security
    user: "1000:1000"
    working_dir: /home/node/app
    command: >
      /bin/bash -c "
        yarn opensearch snapshot
      "
```

2023-04-14 09:23 UTC, AlexRuiz7 requested changes

2023-04-14 09:23 UTC, AlexRuiz7 commented on docker/dev.sh
> +export OPENSEARCH_VERSION=$(bash dev-tools/get-version.sh)
This script is removed in OpenSearch 2.6.0. It's replaced in the `package.json` by Node command instead.

2023-04-17 17:05 UTC, AlexRuiz7 commented on docker/dev.sh
> +export OPENSEARCH_VERSION=$(bash dev-tools/get-version.sh)
As we want the environment to be node-agnostic, using the Node command would not be a solution for use.

Instead, I'll port the bash command in `dev-tools/get-version.sh`. The method to read the OpenSearch version in the `package.json` file will diverge from OpenSearch's, but we are fine with it.

2023-04-17 18:08 UTC, AlexRuiz7 commented on docker/dev.sh
> +export OPENSEARCH_VERSION=$(bash dev-tools/get-version.sh)
Solved in https://github.com/wazuh/wazuh-dashboard/pull/30/commits/ef942756ac5eacecc2fabc25d71bbd6bfa7551a6

2023-04-20 10:59 UTC, Desvelao approved these changes
**review**

:green_circle: code

2023-04-26 13:21 UTC, merged